name: Destroy Infrastructure

# Solo se ejecuta manualmente (botón en GitHub)
on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Escribe "DESTROY" para confirmar la eliminación total'
        required: true
        default: ''

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    # PROTECCIÓN: El job solo corre si escribiste exactamente DESTROY
    if: ${{ github.event.inputs.confirmation == 'DESTROY' }}
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-east-1'
      # Pasamos las variables de Kaggle para que Terraform no falle al leer el plan
      TF_VAR_kaggle_username: ${{ secrets.KAGGLE_USERNAME }}
      TF_VAR_kaggle_key: ${{ secrets.KAGGLE_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # O la versión que estés usando

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform # Ajusta si tu main.tf no está en esta carpeta

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform
